package:
  name: ts-flint
  version: {{ environ.get('GIT_DESCRIBE_TAG', '') }}

source:
  git_url: ../..

build:
  number: {{ environ.get('GIT_DESCRIBE_NUMBER', 0) }}

requirements:
  build:
    - python
    - setuptools
  run:
    - pandas
    - python

test:
  imports:
    - ts.flint

about:
  home: https://www.github.com/twosigma/flint
  summary: Distributed time-series analysis on Spark
